### ISSUE TITLE
"ERROR: Alfred Export List Filter to CSV[Script Filter] Code 127: env: python3: No such file or directory"

### ISSUE THREAD

**Issue by politicus** [mr-pennyworth/alfred-lf2csv#1]
Hi @mr-pennyworth!

I am trying to make your workflow work. The problem is when I hit the keyboard shortcut, Alfred search bar does not show any ready to be dragged-and-dropped .csv file.

Getting the following error message in Alfred Preferences console:

`ERROR: Alfred Export List Filter to CSV[Script Filter] Code 127: env: python3: No such file or directory`

Alfred version: 4.5.1.

**Comment by yellowsoar** [comment]
Open the terminal and execute: ```$ which python3```, then update the shebang.
If you don't have python3 installed, use `brew` or `pyenv` to install python3.

**Comment by politicus** [comment]
@yellowsoar Thank you for your answer! (I didn't any notification of your answer -> my belated answer).
